name: Sync Stellar Forge Stats
on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch: {}
jobs:
  ping-worker:
    runs-on: ubuntu-latest
    steps:
      - run: curl -f https://stellarforge-website.stellar-forge.workers.dev/
